### ISSUE TITLE
[FEATURE] Add way to test a webhook

### ISSUE THREAD

**Issue by cswendrowski** [cswendrowski/HumbleBundleBot#10]
**Is your feature request related to a problem? Please describe.**
Users would like a way to immediately verify that their webhook is working (both Discord and JSON). Currently they have to wait for a scrape.

**Describe the solution you'd like**
A new Function, `TestWebhook(string webhook, int webhookType, string currentBundleName)` should be created. This would load the current bundle of given name (see #9 for info on adding "Current"), then sends to a given webhook with the correct format

**Describe alternatives you've considered**
Rather than passing in a `currentBundleName`, we could just send the most recent bundle we've scraped

**Additional context**
Do we need to consider anti-spam functionality? We currently assume that a webhook is owned by the User. If someone got access to a Webhook they could spam it through our service, but they could do that themselves as well.

**Comment by kamillw23** [comment]
Hello, do you know when you will be able to implement this feature?

**Comment by cswendrowski** [comment]
@kamillw23 I'll take a look at this in the next few days!

**Comment by cswendrowski** [comment]
@kamillw23 This is now available - please see instructions here: https://github.com/cswendrowski/HumbleBundleBot/blob/master/README.md#how-to-test-a-registered-webhook

**Comment by kamillw23** [comment]
Thank you, I will check this tommorow.
