### ISSUE TITLE
[BUG] Non-bundle blog post trips mixed-bundle webhook

### ISSUE THREAD

**Issue by foohonpie** [cswendrowski/HumbleBundleBot#12]
**Describe the bug**
We just got a post from the bot for this update:

https://blog.humblebundle.com/2019/10/23/introducing-humble-choice/

It showed up for a webhook we set up for mixed bundles.

**I am having issues with the following Bundles:**
- Non-Bundle

**I have the following types of Webhooks registered**
- 1) Discord: All of them individually

**Expected behavior**
Expected bot to post updates for individual bundles.

**Screenshots**
<img width="584" alt="Screen Shot 2019-10-23 at 11 08 12 AM" src="https://user-images.githubusercontent.com/674157/67421485-70985e00-f585-11e9-9e50-00e31ec305a4.png">

**Additional context**
None

**Comment by cswendrowski** [comment]
I saw this as well, it's an amusing extension of the bot's behavior. I'll add in a blacklist for any `https://www.humblebundle.com/subscription` URL's discovered for the future

**Comment by cswendrowski** [comment]
@foohonpie update is deploying, we shouldn't see Humble Choice again
