### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Tatakai4evil** [cswendrowski/HumbleBundleBot#13]
Hello, I set up the bot on my discord but wanted to test it to see if it was working (I used the website to register it). However, it seems that the provided test link is no longer working https://humblebundlenotifications.azurewebsites.net/api/TestWebhook

Without this link I do not know how to do an HTTP Post Request for my discord.

**Comment by cswendrowski** [comment]
Apologies for the long delay - you'll need to execute that endpoint via a REST tool such as [Insomnia](https://insomnia.rest)
Regards,
Cody
