### ISSUE TITLE
[FEATURE] Omit bundle updates

### ISSUE THREAD

**Issue by B1zguy** [cswendrowski/HumbleBundleBot#14]
**Is your feature request related to a problem? Please describe.**
I don't think it's possible to set update status to False with the [bot service](humblebundlenotificationssite.azurewebsites.net)?

**Describe the solution you'd like**
The bot currently sends when update each time a bundle is update. It'd be nice to have the option to stop this.

**Describe alternatives you've considered**
I don't run the hosted system thus cannot :)

**Additional context**
Nope. Thanks!

**Comment by cswendrowski** [comment]
@B1zguy when registering on the site, you just uncheck "Send Updates" when registering your webhook

![image](https://user-images.githubusercontent.com/15639841/91641438-0bee3100-e9ea-11ea-8357-e81d10145a68.png)

You can remove your current webhooks then reregister to not have updates
