### ISSUE TITLE
[BUG] Register Webhook fails

### ISSUE THREAD

**Issue by Spiderschwein** [cswendrowski/HumbleBundleBot#16]
Good evening,

**Describe the bug**
I've tried to register a webhook for my Discord Server throug the Web-GUI. This fails with the message "error". 
I've looked in the firefox developer tools and the answer from the server is an error 400 with the body "Please pass in a valid Discord Webhook URL in the request body".

My Webhook URL is "https://discord.com/api/webhooks/78[...]46/_bBS[...]8tEKy4" (Shortend due to privacy reasons)
Notice the URL "discord.com". All examples in the readme i've found is "discordapp.com". Maybe thats the reason the bot dont recognize the webhook as a valid Webhook?

**I am having issues with the following Bundles:**
N/A

**I have the following types of Webhooks registered**
- 0) WebhookType: 0
- 1) Discord: Games
- 2) JSON: Developer Messages

**Expected behavior**
Add the Webhook URL to the bot :)

**Screenshots**
N/A

**Additional context**
Some info about the domain change: https://github.com/discord/discord-api-docs/issues/1585

**Comment by rovendoug** [comment]
I am also receiving this error on attempting to register a webhook. My Webhook URL follows the same format as Spiderschwein:
https://discord.com/api/webhooks/789031[...]6522/IPry-[...]-6K7zygc[...]4hdXt0k48_[...].

**Comment by sawahsawah** [comment]
I am also having this issue!

**Comment by rovendoug** [comment]
@sawahsawah @Spiderschwein I will mention that if you modify the Webhook link domain to be discordapp.com, instead of discord.com, it will work until this big is resolved.

That said, YMMV.

**Comment by sawahsawah** [comment]
@rovendoug That did work for me! Not sure if it was supposed to send something to confirm it was set up (my channel didn't get anything) but I guess we will have to wait and see!

**Comment by rovendoug** [comment]
> @rovendoug That did work for me! Not sure if it was supposed to send something to confirm it was set up (my channel didn't get anything) but I guess we will have to wait and see!

Glad to hear! 

It should work, I didn't receive a confirmation test hook either, but the next bundle that went live, landed in the channels I had set up.

**Comment by Spiderschwein** [comment]
@rovendoug Ah, nice. I will try that! Thanks!

**Comment by cswendrowski** [comment]
This is now resolved - apologies for the delay!

**Comment by Spiderschwein** [comment]
Seems to work now.
Thank you!
