### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by EugeneGGHQ** [cswendrowski/HumbleBundleBot#18]
**Describe the bug**
Appears that game bundles are no longer posting again. 

**I am having issues with the following Bundles:**
Codemasters racing game bundle hasn't auto posted to my discord channel, despite a couple of other bu memes posting successfully earlier in the month (Quebec gaming bundle and Winter Indie Mix

**I have the following types of Webhooks registered**
- 1) Discord: Games

**Expected behavior**
Would expect that the bundle would have auto posted via the bot, but similar to bundles in the last couple of months, it seems to occasionally fail to do so.

**Additional context**
No rush on a fix - I appreciate it's the holiday season - just wanted to let you know before I disappear for Christmas and potentially forget about it!

**Comment by EugeneGGHQ** [comment]
Holiday in Space bundle also didn't post. I believe there's a new Games bundle landing today.

**Comment by cswendrowski** [comment]
This is now resolved - apologies for the delay!
