### ISSUE TITLE
[FEATURE] As a User, I want to be able to register for all bundles at once

### ISSUE THREAD

**Issue by cswendrowski** [cswendrowski/HumbleBundleBot#7]
**Is your feature request related to a problem? Please describe.**
Users often get confused about the "Mixed" bundle type and misinterpret it as an "All" category.

**Describe the solution you'd like**
Explicitly adding a category would both clarify that "Mixed" is different and save Users some setup time

**Describe alternatives you've considered**
Could make this a UI-only feature, but API parity is preferred

**Comment by Saphrym** [comment]
I second this! :)

**Comment by cswendrowski** [comment]
@Saphrym this is now complete!

**Comment by Saphrym** [comment]
Awesome!
